//Adder with 2 qubits input.
OPENQASM 2.0;
include "qelib1.inc";
qreg q[7];
creg meas[7];
ccx q[1],q[2],q[3];
cx q[1],q[2];
ccx q[4],q[5],q[6];
cx q[4],q[5];
ccx q[0],q[2],q[3];
ccx q[3],q[5],q[6];
cx q[0],q[2];
cx q[3],q[5];
measure q[0] -> meas[0];
measure q[1] -> meas[1];
measure q[2] -> meas[2];
measure q[3] -> meas[3];
measure q[4] -> meas[4];
measure q[5] -> meas[5];
measure q[6] -> meas[6];